version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: sakila-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/db/sakila-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./backend/db/sakila-data.sql:/docker-entrypoint-initdb.d/2-data.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sakila-backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://user:password@mysql:3306/sakila"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    container_name: sakila-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql-data:
