version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: sakila-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sakila-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./sakila-data.sql:/docker-entrypoint-initdb.d/2-data.sql

volumes:
  mysql-data:
